version: '3'

services:
  app:
    container_name: app
    build: 
      context: .
      dockerfile: build/dockerfiles/ssh-chess/Dockerfile
    environment:
      - PORT=2022
    ports:
      - "2022:2022"
    networks:
      net:
        ipv4_address: 172.28.0.2
            
networks:
  net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
