version: '3'

services:
  app:
    container_name: app
    build: 
      context: .
      dockerfile: dockerfiles/app/Dockerfile
    environment:
        - RECORDER_HOST=172.28.0.3
    ports:
      - "2022:2022"
    networks:
      net:
        ipv4_address: 172.28.0.4

  db:
    container_name: db
    build: dockerfiles/db/.
    ports:
      - "5432:5432"
    networks:
      net:
        ipv4_address: 172.28.0.2
            
networks:
  net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
